---
title: "빅데이터 분석 시각화 #1"
author: "Jade"
date: '2019년 3월 15일'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)

load('data/data_eng.rda')

theme_set(theme_gray(base_family="AppleGothic"))
par(family = "AppleGothic")
```


## 1. mpg데이터에서 연도별 배기량에 따른 도시/고속도로 연비를 꺽은선으로 그리시오. (단, 2008년은 굵은 선으로 표현하시오)

```{r}
d4 = mpg %>% group_by(year, displ) %>% summarise(m1 = mean(cty), m2 = mean(hwy))
str(d4)
summary(d4)
head(d4)

ggplot(d4, aes(x=displ)) + 
  geom_line(data = d4 %>% filter(year==1999), aes(y=m1, color='1999 cty')) +
  geom_line(data = d4 %>% filter(year==1999), aes(y=m2, color='1999 hwy')) +
  geom_line(data = d4 %>% filter(year==2008), aes(y=m1, color='2008 cty'), size=1) +
  geom_line(data = d4 %>% filter(year==2008), aes(y=m2, color='2008 hwy'), size=1) +
  scale_colour_manual("", breaks = c("1999 cty", "1999 hwy", "2008 cty", "2008 hwy"),
                      values = c("gray", "pink", "blue", "darkblue")) +
  xlab("배기량") +
  scale_y_continuous("연비", limits = c(0, 50)) +
  labs(title = '연도별 통합연비', subtitle = '(굵은선은 2008년)') 
```


## 2. data(성적.csv) 데이터에서 국어 성적이 80점 이상인학생들의 수를 성비가 보이도록 학급별로 막대그래프를 그리시오.

```{r}
summary(data)
head(data)
ggplot(data %>% filter(kor >= 80), aes(cls)) +
  geom_bar(aes(fill=gen), width=0.7) +
  xlab('학급') + ylab('학생수') +
  labs(title = "국어 우수 학생", subtitle = "(80점 이상)", fill='성별')

```

## 3. 국어 성적이 95점 이상인 학생들의 학급별 밀도그래프를 그리시오.

```{r}
ggplot(data[data$kor >= 95, ], aes(kor)) +
  geom_density(aes(fill=factor(cls)), alpha = 0.5) + xlab('국어성적') +
  labs(title = "반별 국어 우수 학생", subtitle = "국어성적 A+", 
       fill='학급', caption = "기준점수 >= 95")
```


## 4. midwest데이터에서 전체인구와
아시아계 인구의 관계를 알아보기 위한
그래프를 그리시오.
(단, 전체인구는 50만명 이하,
   아시아계인구는 1만명 이하만 표시되게)
   
```{r, warning = F, message = F}
ggplot(midwest) + 
  geom_point(aes(x=poptotal, y=popasian), alpha = 0.5) +
  xlab('전체인구') + ylab("아시아계인구") +
  xlim(0, 500000) + ylim(0, 10000) +
  labs(title = "전체인구 대비 아시아계 인구")
```


